# config context path to "/" by setting an empty string
server:
  contextPath:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ziedyazidi
    key-store-type: PKCS12
    key-alias: tomacat

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

  jpa:
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: create

  datasource:
  na
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: pass
    driver-class-name: com.mysql.jdbc.Driver



jwt:
  header: Authorization
  secret: mySecret
  expiration: 1004800
  route:
    authentication:
      path: auth
      refresh: refresh


#logging:
#  level:
#    org.springframework:
#      security: DEBUG